export const ADD_TRIP = 'ADD_TRIP';
export const REMOVE_TRIP = 'REMOVE_TRIP';
export const UPDATE_TRIPS = 'REMOVE_TRIP';
export const STORAGE_STORE_TRIP = 'STORAGE_STORE_TRIP';
export const STORAGE_UPDATE_TRIP = 'STORAGE_UPDATE_TRIP';
export const STORAGE_DESTROY_TRIP = 'STORAGE_DESTROY_TRIP';